- name:  Set default ruby version
  shell: rbenv global {{ ruby_default_version }}
  when:  ruby_default_version is defined

- name:  Forbid gem documentation
  copy:  src=gemrc.yml
         dest={{ ansible_env.HOME }}/.gemrc
         owner={{ ansible_env.USER }}
         group={{ ansible_env.USER }}
         mode=0644
  when:  ruby_forbid_gem_docs

- name:  Rehash gem binaries
  shell: rbenv rehash
  when:  ruby_version_installed|changed
