- name:          Check version installation
  shell:         rbenv versions | grep {{version}}
  ignore_errors: yes
  register:      version_already_installed

- name:          Install version
  shell:         rbenv install {{version}}
  register:      version_installed
  when:          version_already_installed|failed

- include: extras.yml
