- name:          Check installed ruby versions
  shell:         rbenv versions | grep {{ ruby_version }}
  ignore_errors: yes
  register:      ruby_version_already_installed

- name:          Install ruby version
  shell:         rbenv install {{ ruby_version }}
  register:      ruby_version_installed
  when:          ruby_version_already_installed|failed

- include: extras.yml
